@startuml

skinparam componentStyle uml1

left to right direction

node "Agregador" {

    database Colecciones
    database SolicitudesDeEliminacion

    interface "Aceptar/RechazarSolicitudDeEliminacion(solicitud)" as interfazSolicitudesEliminacion
    interface "Contribuir(hecho) / \n AgregarSolicitud(solicitud)" as interfazContribucion
    interface "VerHechosFiltrados(coleccion, filtro)"

    [Dominio] -- Colecciones
    [Dominio] -- SolicitudesDeEliminacion
    interfazSolicitudesEliminacion -- [Dominio]

    "VerHechosFiltrados(coleccion, filtro)" -- [Dominio]
    interfazContribucion -- [Dominio]
}

node "FuenteEstatica" {

    interface "ObtenerHechos(filtro)" as InterfazFuenteEstatica

    database Archivo

    [Procesador] as procesadorFuenteEstatica

    InterfazFuenteEstatica -- procesadorFuenteEstatica
    procesadorFuenteEstatica  -- Archivo

    [Dominio] -- InterfazFuenteEstatica
}

node "FuenteProxy" {
    interface "ObtenerHechos(filtro)" as InterfazFuenteProxy

    [Procesador] as procesadorFuenteProxy

    InterfazFuenteProxy -- procesadorFuenteProxy
    [Dominio] -- InterfazFuenteProxy

}

node "FuenteDinamica" {
    interface "Aceptar/RechazarSolicitudDeCambio(solicitud)" as interfazSolicitudesCambio
    interface "Agregar/EliminarHecho(hecho)" as interfazHechos
    interface "ObtenerHechos(filtro)" as interfazFuenteDinamica

    database Hechos
    database SolicitudesDeCambio

    [Procesador] as procesadorFuenteDinamica

    interfazFuenteDinamica -- procesadorFuenteDinamica
    interfazSolicitudesCambio -- procesadorFuenteDinamica
    interfazHechos -- procesadorFuenteDinamica
    procesadorFuenteDinamica -- Hechos
    procesadorFuenteDinamica -- SolicitudesDeCambio

    [Dominio] -- interfazFuenteDinamica
}



 cloud "Servicio Externo / \n Instancia MetaMapa" as conexion
 procesadorFuenteProxy -- conexion

 actor "Usuario" as user
 user -- interfazContribucion
 user -- "VerHechosFiltrados(coleccion, filtro)"

 Actor "Administrador" as admin
 user <|- admin
 admin -- interfazSolicitudesEliminacion
 admin -- interfazSolicitudesCambio
 admin -- interfazHechos


@enduml