@startuml
left to right direction

actor Visualizador
actor Administrador
actor Contribuyente


rectangle #line.dashed {
 usecase "Ver colección" as UC1
 usecase "Evaluar solicitudes" as UC2
 usecase "Crear colección" as UC3
 usecase "Crear fuente" as UC4
 usecase "Crear hecho" as UC5
 usecase "Editar hecho" as UC6
 usecase "Eliminar hecho de Fuente Dinámica" as UC7
 usecase "Asocia algoritmo de \n consenso a una coleccion" as UC8

 usecase "Generar solicitud" as UC1.1
}

Visualizador -- UC1
Administrador -- UC2
Administrador -- UC3
Administrador -- UC4
Administrador -- UC7
Administrador -- UC8
Contribuyente -- UC5
Contribuyente -- UC6



UC1 <.. UC1.1 : <extends>

@enduml