@startuml MetaMapa

class Usuario {
    +(nombre)
    +(apellido)
    +(edad)
    +esContribuyente
    --
    +contribuir()
}

class Administrador {
    +nombre
    +apellido
    +edad
}

class SolicitudDeEliminacion {
    +hecho
    +fundamentacion
    +responsable
    -solicitudesDeEliminacionRepo
    --
    +aceptar(admin)
    +rechhazar(admin)
}

interface SolicitudDeEliminacionRepo {
    --
    +getPendientes()
    +getRechazadas()
    +getRechazos(hecho)
    +hechosEliminados()
}

interface DetectorDeSpam {
    --
    +esSpam(solicitud)
}


class Coleccion {
    +titulo
    +descripcion
    +id
    -criterioDePertenencia
    -fuente
    --
    +hechos(filtro)
}

interface Fuente {
    --
    +obetenerHechos(filtro)
}

class Hecho {
    +titulo
    +descripcion
    +categoria
    +latitud
    +longitud
    +fechaAcontecimiento
    +fechaCarga
    +origen
    +(usuario)
    +(multimedia)
    --
}

enum Origen {
    MANUAL
    DATASET
    CONTRIBUYENTE
}

class FuenteEstatica {
    -pathArchivo
    --
    -crearHechoDesdeFila()
}

interface Filtro {
    +asPredicate()
    +toQueryParam(prefix, delimiter, suffix)
}

abstract class fuenteProxyCalendarizada {
    -refreshTime
    +hechos
    --
    +init()
    -acumularHechos()
    #getNewHechos(ultimaLlamada) {abstract}
}

class fuenteDemo {
    -url
    -conexionDemo
    --
    -parseHehco(fila)
}

class fuenteMetaMapa {
    -path
    -conexionMetaMapa
    --
    +obetenerHechosDeColeccion(coleccion, filtro)
    +enviarSolicitudDeEliminacion(solicitud)
}


Administrador -r-|> Usuario


Coleccion --> Fuente
Coleccion .r.> Filtro

Fuente -l-> "*" Hecho
Fuente .r.>Filtro

FuenteEstatica .u.|> Fuente
fuenteProxyCalendarizada .u.|> Fuente
fuenteMetaMapa .u.|> Fuente
fuenteDemo -u-|> fuenteProxyCalendarizada


Hecho -l-> Origen

SolicitudDeEliminacion --> Hecho
SolicitudDeEliminacion -u-> Administrador

SolicitudDeEliminacionRepo *-- SolicitudDeEliminacion
DetectorDeSpam <-- SolicitudDeEliminacionRepo
SolicitudDeEliminacionRepo <-- Coleccion


@enduml