@startuml MetaMapa

class Usuario {
    nombre
    apellido
    edad
    esContribuyente: bool
    --
    verHechosFiltrados(coleccion, filtro)
    crearSolicitud(hecho,fundamentacion)
    verHechos(Coleccion)
}

class Administrador {
--
    crearColeccion(titulo,descripcion,criterio,fuente)
    verSolicitudes()
    crearFuenteEstatica(pathArchivo)
    aceptarSolicitud(solicitud)
    rechazarSolicitud(solicitud)

}

class Solicitud {
    hecho
    fundamentacion
    solicitudes
    responsable
    --
    aceptar(admin)
    rechhazar(admin)

}

class Solicitudes{
    pendientes[]
    aceptadas[]
    rechazadas[]
    --
    estaEliminado(hecho)
    hechosEliminados()
}

class Coleccion {
    titulo
    descripcion
    criterioDePertenencia
    fuente
    --
    hechos(filtro)
    condicionNoEliminados()
}

interface Fuente {
    --
    obetenerHechos(filtro)
}

class FuenteEstatica {
    pathArchivo
    --
    crearHechoDesdeFila()
    estaRepetido(unHecho, hechos)
}

class Hecho {
    titulo
    descripcion
    categoria
    latitud
    longitud
    fechaAcontecimiento
    fechaCarga
    origen
    --
}

enum Origen {
    MANUAL
    DATASET
    CONTRIBUYENTE
}

enum Filtro {
  TITULO
  DESCRIPCION
  CATEGORIA
  LATITUD_MAYOR
  LATITUD_MENOR
  LONGITUD_MAYOR
  LONGITUD_MENOR
  FECHA_CARGA_ANTES
  FECHA_CARGA_DESPUES
  FECHA_HECHO_ANTES
  FECHA_HECHO_DESPUES
  --
  crearFiltro(valor)
  contiene(Function<hecho, getter, valor)
  compararDouble(Function<Hecho,getter,valor,cmp)
  compararFecha(Function<Hecho,getter,valor,cmp)
}

Administrador -r-|> Usuario

Administrador ..> Coleccion
Administrador .l.> Solicitudes
Administrador ..> FuenteEstatica
Administrador ..>Solicitud

Usuario ..> Coleccion
Usuario ..>Filtro


Coleccion --> Fuente
Coleccion .l.> Solicitudes
Coleccion .r.> Filtro

Fuente -l-> "*" Hecho
Fuente .r.>Filtro

FuenteEstatica .u.|> Fuente
FuenteEstatica .u.> Hecho


Hecho --> Origen

Solicitud --> Hecho
Solicitud -u-> Administrador

Solicitudes -->"*" Solicitud
Solicitudes ..> Hecho



' TODO Preguntas:

'   Implementacion de las etiquetas

'   Una coleccion puede tener mas de una fuente?

'   Las fuentes van a buscar los datos cada vez que se les hace una consulta
'   o guardan los datos de manera local?

'   Tiene sentido inlucluir clases en el diagrama que no se van a aplicar en esta entrega?

@enduml