@startuml

skinparam componentStyle uml1

left to right direction

node "Agregador" {

    database hechos

    interface "Aceptar/RechazarSolicitudDeEliminacion(solicitud)" as interfazSolicitudesEliminacion
    interface "ObtenerHechos(filtro)"

    interfazSolicitudesEliminacion -- [Modelo]

    "ObtenerHechos(filtro)" -- [Modelo]

    [Modelo] -- hechos
}

node "FuenteEstatica" {

    interface "ObtenerHechos(filtro)" as InterfazFuenteEstatica

    database Archivo

    [Procesador] as procesadorFuenteEstatica

    InterfazFuenteEstatica -- procesadorFuenteEstatica
    procesadorFuenteEstatica  -- Archivo

    [Modelo] -- InterfazFuenteEstatica
}

node "FuenteProxy" {
    interface "ObtenerHechos(filtro)" as InterfazFuenteProxy

    [Procesador] as procesadorFuenteProxy

    InterfazFuenteProxy -- procesadorFuenteProxy
    [Modelo] -- InterfazFuenteProxy

}

node "FuenteDinamica" {
    interface "Aceptar/RechazarSolicitudDeCambio(solicitud)" as interfazSolicitudesCambio
    interface "Agregar/EliminarHecho(hecho)" as interfazHechos
    interface "ObtenerHechos(filtro)" as interfazFuenteDinamica

    database Hechos
    database SolicitudesDeCambio

    [Procesador] as procesadorFuenteDinamica

    interfazFuenteDinamica -- procesadorFuenteDinamica
    interfazSolicitudesCambio -- procesadorFuenteDinamica
    interfazHechos -- procesadorFuenteDinamica
    procesadorFuenteDinamica -- Hechos
    procesadorFuenteDinamica -- SolicitudesDeCambio

    [Modelo] -- interfazFuenteDinamica
}



 cloud "Servicio Externo / \n Instancia MetaMapa" as conexion
 procesadorFuenteProxy -- conexion

 actor "Usuario" as user
 user -- "ObtenerHechos(filtro)"

 Actor "Administrador" as admin
 user <|- admin
 admin -- interfazSolicitudesEliminacion
 admin -- interfazSolicitudesCambio
 admin -- interfazHechos


@enduml